spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: luck516136
    driver-class-name: com.mysql.cj.jdbc.Driver

# jpa setting  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      jdbc:
        time_zone: GMT+08:00
    show-sql: true
# spring security
  security:
    user:
      name: admin
      password: 123456
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    session:
      timeout: 60m
  port: 8080



    
    
  